services:
  auth:
    build: ./auth
    tty: true
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

networks:
  backend: